sudo: false

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot

language: scala

jdk:
  - oraclejdk8

script:
  - sbt clean coverage test &&
    sbt coverageAggregate

after_success:
  - sbt coveralls
