language: scala
scala:
  - 2.11.1
script:
  - sbt "runMain Eff exampleProjects/cxf"
  - sbt "runMain Eff exampleProjects/slf4j"
  - sbt "runMain Eff exampleProjects/multi"
  - sbt "runMain Eff exampleProjects/logback"
  - sbt "runMain Eff exampleProjects/thrift"
jdk:
  - oraclejdk8
